name: Haskell CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  ci-enumerate:
    name: Enumerate GHC Versions
    runs-on: ubuntu-latest
    outputs:
      plan: $
    steps:
    - uses: actions/checkout@v3
      with:
        ref: $
    - name: Enumerate CI plans
      id: list-ci
      uses: actions/github-script@v6
      with:
        script: |
          const script = require('./ci/scripts/enumerate-ci.js')
          await script({github, context, core, glob, io, require})

  build:
    name: Build ($)
    needs: [ci-enumerate]
    continue-on-error: true
    strategy:
      matrix:
        plan: $
      fail-fast: false
    env:
      cabal-version: 3.14.2.0
      cabal: "cabal --project-file=$"
      ghc: $
      project-file: $
      plan: $
      artifact-name: "artifact-$"
    runs-on: ubuntu-latest
    outputs:
      benchmarks: $
      tests: $
      artifact: "artifact-$"
    steps:
    - uses: actions/checkout@v3
      with:
        ref: $
    - name: Calculate hash keys
      uses: actions/github-script@v6
      id: cache-keys
      with:
        script: |
          const script = require('./ci/scripts/calc-cache-keys.js')
          await script({ os: "ubuntu", plan: $, path: $, core, glob })

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        enable-stack: false
        cabal-version: $
        ghc-version: $
    - name: Restore ~/.cabal/store
      uses: actions/cache/restore@v4
      with:
        path: ~/.cabal/store
        key: $
        restore-keys: $
    - name: Restore dist-newstyle
      uses: actions/cache/restore@v4
      with:
        path: dist-newstyle
        key: $
        restore-keys: $
    - name: cabal configure
      run: |
        $ v2-configure --enable-tests --enable-benchmarks --enable-optimisation=2
        $ update
    - name: Build Dependencies
      run: | 
        $ build --only-dependencies all
    - name: Save ~/.cabal/store Cache
      uses: actions/cache/save@v4
      with:
        path: ~/.cabal/store
        key: $
    - name: Build All
      run: | 
        $ build all
    - name: Save dist-newstyle Cache
      uses: actions/cache/save@v4
      with:
        path: dist-newstyle
        key: $

    - name: Collect binaries
      continue-on-error: true
      run: bash ./ci/scripts/collect-bins.sh "$"
    - name: Upload Aritracts
      uses: actions/upload-artifact@v4
      with:
        path: $.tar.zst
        name: $
        retention-days: 1
    - name: Upload dist directory (for doctest)
      uses: actions/upload-artifact@v4
      with:
        path: dist-newstyle
        name: dist-newstyle-$
    - name: Upload ~/.cabal/store directory (for doctest)
      uses: actions/upload-artifact@v4
      with:
        path: ~/.cabal/store
        name: store-$
    - name: List Binaries
      id: list-bins
      shell: bash
      run: |
        echo "benchs=$(jq -cMnR '[inputs]' <"$"/benchs.list)" >>"${GITHUB_OUTPUT}"
        echo "tests=$(jq -cMnR '[inputs]' <"$"/tests.list)" >>"${GITHUB_OUTPUT}"

  test:
    name: Test ($)
    needs: [ci-enumerate, build]
    continue-on-error: $
    strategy:
      matrix:
        plan: $
      fail-fast: false
    env:
      cabal: 3.14.2.0
      ghc: $
      project-file: $
      plan: $
      artifact: artifact-$
      dist-name: dist-newstyle-$
      store: store-$
    runs-on: ubuntu-latest
    steps:
      - name: Fail when Corresponding Build didn't succeed
        if: $
        run: echo "BUILD FAILED" >&2; exit 1
      - uses: actions/checkout@v3
        with:
          ref: $
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          name: $
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: $
          path: dist-newstyle
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: $
          path: ~/.cabal/store
      - name: Decompress and locate artifacts
        run: |
          ls -R "$"
          tar xaf "$/$.tar.zst"
          cp "$"/.ghc.environment.* .
          ls -R
      - name: Run Tests
        shell: bash
        run: |
          set -euo pipefail
          TOTAL=0
          SUCCESS=0
          FAIL=0
          while read -r TEST; do
            TOTAL=$((TOTAL + 1))
            echo "--------"
            echo "Running: ${TEST}"
            set +e
            $/tests/"${TEST}"
            RESL=$?
            set -e
            if [ ${RESL} -eq 0 ]; then
              SUCCESS=$((SUCCESS + 1))
              echo "Result: Successed"
            else
              FAIL=$((FAIL + 1))
              echo 'Result: FAILED!'
            fi
          done <$/tests.list

          echo ""
          echo "----"

          if [ "${FAIL}" -eq 0 ]; then
            echo "All ${TOTAL} tests passed."
          else
            echo "${FAIL} out of ${TOTAL} tests FAILED"'!'
            exit 1
          fi

  fourmolu:
    name: Fourmolu
    runs-on: ubuntu-latest
    steps:
      # Note that you must checkout your code before running fourmolu/fourmolu-action
      - uses: actions/checkout@v2
      - uses: fourmolu/fourmolu-action@v10
        with:
          pattern: |
            **/*.hs
            !**/Setup.hs
            !**/Setup.lhs
            !dist-newstyle/**
        
  cabal-check:
    name: Cabal Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        cabal-version: 3.14.2.0
        ghc-version: latest
    - run: cabal check
